[tool.poetry]
name = "django-auctions"
version = "0.1.0"
description = "Django Auctions Project"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.5"
djangorestframework = "^3.14.0"
django-cors-headers = "^4.3.1"
python-dotenv = "^1.0.1"
gunicorn = "^21.2.0"
whitenoise = "^6.6.0"
markdown = "^3.5.2"
django-filter = "^23.5"
pillow = "^10.2.0"
django-storages = "^1.14.2"
boto3 = "^1.34.46"
cachetools = "^5.5.2"
certifi = "^2025.1.31"
charset-normalizer = "^3.4.1"
google-auth = "^2.38.0"
google-auth-oauthlib = "^1.2.1"
idna = "^3.10"
oauthlib = "^3.2.2"
pyasn1 = "^0.6.1"
pyasn1-modules = "^0.4.1"
python-http-client = "^3.3.7"
requests = "^2.32.3"
requests-oauthlib = "^2.0.0"
rsa = "^4.9"
sendgrid = "^6.11.0"
starkbank-ecdsa = "^2.2.0"
django-ses = "^4.4.0"
django-csp = "^3.7"
psycopg2-binary = "^2.9.9"
celery = "^5.4.0"
django-celery-beat = "^2.7.0"
redis = "5.0.1"
<<<<<<< HEAD
django-silk = "^5.1.0"
=======
django-redis = "^5.4.0"
hiredis = "^2.3.2"
django-debug-toolbar = "^4.3.0"  # Use the latest version available
>>>>>>> 02a5e0e (unfixable trash frontend)

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"
pytest-django = "^4.8.0"
coverage = "^7.4.1"
black = "^24.1.1"
flake8 = "^7.0.0"
pylint = "^3.0.3"
pylint-django = "^2.5.5"
isort = "^5.13.2"
mypy = "^1.8.0"
django-stubs = "^4.2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
# Exclude these patterns
/(
 \.git
 | \.hg
 | \.mypy_cache
 | \.tox
 | \.venv
 | _build
 | buck-out
 | build
 | dist
 | migrations
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip = ["migrations"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = ["test_*.py", "*_test.py"]
addopts = "-v -p no:warnings"
testpaths = ["tests"]

[tool.coverage.run]
source = ["."]
omit = [
 "*/tests/*",
 "*/migrations/*",
 "manage.py",
 "*/asgi.py",
 "*/wsgi.py",
 "*/settings.py",
]

[tool.pylint.main]
load-plugins = ["pylint_django"]
django-settings-module = "core.settings"

[tool.pylint.format]
max-line-length = 88

[tool.pylint.messages_control]
disable = [
 "C0111", # missing-docstring
 "C0103", # invalid-name
 "C0330", # bad-continuation
 "C0326", # bad-whitespace
 "R0903", # too-few-public-methods (for Django models)
 "W0511", # TODO warning
 "W0703", # broad-except
 "R0913", # too-many-arguments
 "R0914", # too-many-locals
 "W0221", # arguments-differ
 "C0415", # import-outside-toplevel (common in Django)
]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
python_version = "3.11"
strict = true
ignore_missing_imports = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true
implicit_reexport = false

[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "core.settings"
package-mode = false