name: youtuber-bidding-api
services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
    env_file:
      - ../env/.env.dev
    ports:
      - "8000:8000"
    networks:
      - youtuber-bidding
  youtuber-bidding-api-db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=youtuber_bidding_dev
    ports:
      - "5432:5432"
    networks:
      - youtuber-bidding
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - youtuber-bidding
volumes:
  postgres_data:
networks:
  youtuber-bidding:
    external: true