name: youtuber-bidding-api
services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
    env_file:
      - ../env/.env.dev
    ports:
      - "8000:8000" 
    networks:
      - youtuber-bidding
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=youtuber_bidding_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - youtuber-bidding

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - youtuber-bidding
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    sysctls:
      - net.core.somaxconn=511

networks:
  youtuber-bidding:
    external: true

volumes:
  postgres_data:
