name: youtuber-bidding-api
services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
    env_file:
      - ../env/.env.dev
    ports:
      - "8000:8000"
    networks:
      - youtuber-bidding
    environment:
      - DEBUG=True  # Add this explicitly  
networks:
  youtuber-bidding:
    external: true
