# Generated by Django 5.1.6 on 2025-03-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_user_managers_item_winner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
