# Generated by Django 5.1.6 on 2025-03-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
