# Generated by Django 5.1.6 on 2025-03-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_itemimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemimage",
            name="original_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(upload_to="item_images/"),
        ),
    ]
