# Generated by Django 5.1.6 on 2025-03-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_itemimage_original_url_alter_itemimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemimage",
            name="original_url",
        ),
    ]
