# Generated by Django 5.1.6 on 2025-03-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_remove_itemimage_original_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemimage",
            options={},
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
