# Generated by Django 5.1.6 on 2025-03-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_itemimage_options_alter_itemimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemimage",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="user",
            name="outbid_notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="win_notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(upload_to="items/"),
        ),
    ]
