# Generated by Django 5.1.6 on 2025-03-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_itemimage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemimage",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="outbid_notifications_enabled",
        ),
        migrations.RemoveField(
            model_name="user",
            name="win_notifications_enabled",
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
