# Generated by Django 5.1.6 on 2025-03-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_itemimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="outbid_notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="win_notifications_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
