# Generated by Django 5.1.6 on 2025-03-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_user_outbid_notifications_enabled_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemimage",
            options={"ordering": ["order"]},
        ),
    ]
