# Generated by Django 5.1.6 on 2025-03-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_itemimage_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["end_date"], name="auctions_it_end_dat_ce6998_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["is_active"], name="auctions_it_is_acti_8b20ab_idx"
            ),
        ),
    ]
