# Generated by Django 5.1.6 on 2025-03-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_item_auctions_it_end_dat_ce6998_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["category"], name="auctions_it_categor_3959a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["created_at"], name="auctions_it_created_df60e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["is_active", "end_date"], name="auctions_it_is_acti_d3f09f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["category", "is_active"], name="auctions_it_categor_74dd01_idx"
            ),
        ),
    ]
