# Generated by Django 5.1.6 on 2025-03-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_item_auctions_it_end_dat_ce6998_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["category"], name="auctions_it_categor_d4f450_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["end_date", "is_active"], name="auctions_it_end_dat_is_act_e33712_idx"
            ),
        ),
    ]
