# Generated by Django 5.1.6 on 2025-03-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_item_auctions_it_categor_3959a8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemimage",
            name="webp_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="itemimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
