# Generated by Django 5.1.6 on 2025-03-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_add_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="auctions_it_categor_3959a8_idx",
            old_name="auctions_it_categor_d4f450_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="auctions_it_end_dat_bd6e79_idx",
            old_name="auctions_it_end_dat_is_act_e33712_idx",
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="end_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["item", "amount"], name="auctions_bi_item_id_5a66ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["user", "created_at"], name="auctions_bi_user_id_a17c47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["winner"], name="auctions_it_winner__87c1b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["current_price"], name="auctions_it_current_6491fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["created_at"], name="auctions_it_created_df60e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["category", "end_date"], name="auctions_it_categor_f8a429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["category", "is_active", "end_date"],
                name="auctions_it_categor_0349bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "receiver", "is_read"],
                name="auctions_me_sender__446159_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="auctions_me_created_54b57c_idx"
            ),
        ),
    ]
